config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'
  mount ShopifyApp::Engine, at: '/'
  post 'app_uninstall' => "custom_webhooks#app_uninstall"
  get 'product_variants' => "scripts#product_variants"
  get 'plan_active' => "home#plan_active"
  get 'activatecharge' => 'home#activatecharge'
  get 'home' => 'home#index'
  get 'update_script' => "scripts#update_script"
  # get 'product_variant' => "custom_scripts#product_variant"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  include ShopifyApp::Shop
  include ShopifyApp::SessionStorage

  after_create :set_welcome
  
  def set_welcome
  	self.set_store_session
  	current_shop = ShopifyAPI::Shop.current.try(:attributes)
		UserMailer.install_app(current_shop[:email], current_shop).deliver_now rescue nil
  end

	def set_store_session
		sess = ShopifyAPI::Session.new(self.shopify_domain, self.shopify_token)
		ShopifyAPI::Base.activate_session(sess)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ShopifyApp::LoginProtection
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def setup_session
  	if params[:shop].present?
	  	domain = params[:shop]
	    @shop = Shop.find_by_shopify_domain(domain)
	    @shop.set_store_session if @shop.present?
	end
  end
end

app/controllers/custom_scripts_controller.rb
class CustomScriptsController < ApplicationController
	skip_before_action :verify_authenticity_token

  def product_variant
    respond_to do |format|
      format.html { }
      format.json { }
      format.js { }
    end
  end

end

app/controllers/custom_webhooks_controller.rb
class CustomWebhooksController < ApplicationController
	#before_action :set_session
  include ShopifyApp::WebhookVerification

  def app_uninstall
    puts params.inspect
    # Shop.where(shopify_domain: params[:domain]).destroy_all
    UserMailer.uninstall_app(params[:email], params).deliver_now rescue nil
  end

end

app/controllers/home_controller.rb
class HomeController < ShopifyApp::AuthenticatedController

  def index
    current_domain = ShopifyAPI::Shop.current
    @shop = Shop.find_by_shopify_domain(params[:shop]||current_domain.domain)
    @product_count = ShopifyAPI::Product.find(:all).count
    if @shop.present?
      if @product_count > 5
        @plan_activeded = ShopifyAPI::RecurringApplicationCharge.current.present?
        unless @plan_activeded
          @shop.update(enable: false)
        end
      else
        @plan_activeded = false
      end
      if params.keys.include?('enable_shop')
        @shop.update(enable: params[:enable_shop])
      end
    end
  end

  def plan_active
      # checks to see if there is already an RecurringApplicationCharge created and activated
      @url = root_path
      unless ShopifyAPI::RecurringApplicationCharge.current
        recurring_application_charge = ShopifyAPI::RecurringApplicationCharge.new(
                name: "Unlimited Plan",
                price: 0.5,
                return_url: "https://multi-image-variants.herokuapp.com/activatecharge",
                test: true,
                trial_days: 7,
                terms: "$0.5 for unlimited product")

        # if the new RecurringApplicationCharge saves,redirect the user to the confirmation URL,
        # so they can accept or decline the charge
        if recurring_application_charge.save
          @url = recurring_application_charge.confirmation_url
        end
      end
  end 

  def activatecharge
    # store the charge_id from the request
    recurring_application_charge = ShopifyAPI::RecurringApplicationCharge.find(request.params['charge_id'])
    if recurring_application_charge.status == "accepted"
    	recurring_application_charge.activate
    end
    redirect_to root_path
  end 

end

app/controllers/scripts_controller.rb
class ScriptsController < ApplicationController

	def product_variants
		puts params.inspect
		@shop = Shop.find_by_shopify_domain(params[:shop])
	    respond_to do |format|
	      format.html { }
	      format.json { }
	      format.js {}
	    end
	end

	def update_script
		shop = Shop.find_by_id(params[:shop_id])
		if shop.present?
			shop.update(enable: params[:enable_shop])
		end
	end

	def index
	    @product_count = ShopifyAPI::Product.find(:all).count
	    if @product_count > 5
	    	@plan_activeded = ShopifyAPI::RecurringApplicationCharge.current.present?
	    	unless @plan_activeded
	    		@shop.update(enable: false)
	    	end
	    else
	    	@plan_activeded = false
	    end
	    if params.keys.include?('enable_shop') && @shop.present?
	    	@shop.update(enable: params[:enable_shop])
	    end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/custom_scripts/product_variant.html.haml
:plain
  function change_images(){
    variant_id = $($("select[id*='product-select-']").slice(-1)[0]).val();
    variant_images = variants[variant_id];
    $.each(product_images, function( index, image ) {
      var par_url = image.src.split('.jpg?')[0];
      var obj = $("img[src*='"+par_url.replace('https:','')+"']");
      if($.inArray(image, variant_images) !== -1){
        obj.parent().show()
      }else{
        obj.parent().hide();
      }
    })
  }

  if(window.location.href.toLowerCase().indexOf("/products/") >= 0){
    variants = {}
    product_images = []
    $.getJSON( "/products/"+window.location.href.split('/').slice(-1)[0], function( data ) {
      var product = data.product;
      product_images = product.images;
      var varinat_image_ids = $.map( product.variants, function( n, i ) {
        return n.image_id;
      });
      var product = data.product
      $.each(product.variants, function( index, varant ) {
      variants[varant.id] = [];
      if(varant.image_id != null){
        var enable_image = false;
        $.each(product.images, function( index, image ) {
          if(image.id == varant.image_id){
            variants[varant.id].push(image)
            enable_image = true
          }else{
            if(enable_image == true){
              if($.inArray(image.id, varinat_image_ids) !== -1){
                enable_image = false
              }else{
                variants[varant.id].push(image)
              }
            }
          }
        });
      }
      });
      change_images();
    });
    $("select[id*='product-select-']").on('change',function() {
      change_images();
    })
  }

app/views/custom_scripts/product_variant.js.haml
:plain
	function change_images(){
		variant_id = $($("select[id*='product-select-']").slice(-1)[0]).val();
		variant_images = variants[variant_id];
		$.each(product_images, function( index, image ) {
			var par_url = image.src.split('.jpg?')[0];
			var obj = $("img[src*='"+par_url.replace('https:','')+"']");
			if($.inArray(image, variant_images) !== -1){
				obj.parent().show()
			}else{
				obj.parent().hide();
			}
		})
	}

	if(window.location.href.toLowerCase().indexOf("/products/") >= 0){
		variants = {}
		product_images = []
		$.getJSON( "/products/"+window.location.href.split('/').slice(-1)[0], function( data ) {
			var product = data.product;
			product_images = product.images;
			var varinat_image_ids = $.map( product.variants, function( n, i ) {
			  return n.image_id;
			});
			var product = data.product
			$.each(product.variants, function( index, varant ) {
			variants[varant.id] = [];
			if(varant.image_id != null){
				var enable_image = false;
				$.each(product.images, function( index, image ) {
					if(image.id == varant.image_id){
						variants[varant.id].push(image)
						enable_image = true
					}else{
						if(enable_image == true){
							if($.inArray(image.id, varinat_image_ids) !== -1){
								enable_image = false
							}else{
								variants[varant.id].push(image)
							}
						}
					}
				});
			}
			});
			change_images();
		});
		$("select[id*='product-select-']").on('change',function() {
			change_images();
		})
	}

app/views/home/index.html.erb
<script type="text/javascript">
    $( document ).ready(function() {
		jQuery("#masterSwitch").on('change',function() {
		   window.location = "/?enable_shop="+jQuery(this).is(':checked');
		});
		if(jQuery("#masterSwitch").attr('value') == 'true'){
			jQuery("#masterSwitch").attr('checked', true)
		}else{
			jQuery("#masterSwitch").attr('checked', false)
		}
	});
</script>

<div class="row">
	<div class="col-sm-8 mid-col" style="padding-right: 0;">
		<section class="banner">
			<div class="banner-message text-center">
				<h1>Hello, <%=ShopifyAPI::Shop.current.shop_owner if @shop.present?%></h1>
				<p>Welcome to Variant Image Automator</p>
				<p class="small">
					Handcrafted by <strong>StarApps</strong>
				</p>
			</div>
		</section>
		<section class="setup-wrapper wrapper-padding">
			<div class="card">
				<div class="row" style="margin: 0">
					<div class="col-sm-4" id="videoTrigger" title="Play video" style="padding-left: 0; padding-right: 0;">
					    <%= image_tag 'video_thumb.png', class: 'img-responsive video-thumb'%>
					</div>
					<div class="col-sm-12 video-player" id="videoPlayer">
						<span id="closeVideo" class="close">x</span>
						<iframe width="100%" height="450" frameborder="0" allowfullscreen></iframe>
					</div>
					<div class="col-sm-8" id="videoInfo">
						<div class="card-inner">
							<h3 class="card-header">Setting up the app and products</h3>
							<p>
								This app will automatically hide images of variants not selected, after you arrange the variant images in order. Take a quick minute to learn how to arrange the product images and then it's on autopilot! 
							</p>
						</div>
					</div>
				</div>
			</div>
		</section>
		<section class="faq-wrapper wrapper-padding">
			<div class="card">
				<div class="card-inner">
					<h3 class="card-header">Frequently Asked Questions (FAQs)</h3>
					<ul class="faq-list">
						<li>
							<strong>Do i Need to change any liquid file or manually install a code?</strong>
							<p>
								No, Variant Image Automator App doesn’t require any modification in theme files.
							</p>
						</li>
						<li>
							<strong>Which themes do you support?</strong>
							<p>
								The following themes are known to work with Variant Image Automator.
								Responsive, Retina, District, Focal, Atlantic, Symmetry, Blockshop, Vantage, Sunrise, Mr Parker, ShowTime, Fashionopolism, Startup, Canopy, Editions, Expression, Envy, Colors, Alchemy, Label, Launch, Flow.
								<br/><br/>
								We are actively working to add more themes in the list, If your theme is not listed or you are having trouble with installation, send us an email to apps@starapps.studio ad we'll try our best to make it work for you.
							</p>
						</li>
						<li>
							<strong>I have products with different type of options, will that be an issue?</strong>
							<p>
								Absolutely not, the app supports upto 3 options in a product. It doesn’t matter how many different type of options you provide for different products, the app handles all of them automatically.
							</p>
						</li>
						<li>
							<strong>I have multiple images for each variant, is there any maximum limit that I can use?</strong>
							<p>
								No, you can use as many image for a variant as you wish.
							</p>
						</li>
						<li>
							<strong>Will this app reduce performance of my website or increase page load time?</strong>
							<p>
								We add a very small code in your product page and keep interactions with our server at minimum, this will not increase your page load time or affect performance.
							</p>
						</li>
					</ul>
				</div>
			</div>
		</section>
	</div>
	<div class="col-sm-4 right-col" style="padding-left: 0;">
		<div class="side-wrap">
			<div class="sidebar-wrapper">
				<ul class="sidebar-items">
					<li>
						<h3 class="card-header">
							Loving the App ?
							<%= image_tag 'heart.png'%>
						</h3>
						<p>
							Why not <a href="#">leave us a positive review!</a><br/>
							They're the main way we get recognized, and we give high-fives when we get one!
						</p>
					</li>
					<li>
						<h3 class="card-header">
							Say Hello :)
						</h3>
						<p>
							If you have a Question/ want to send us a Feedback/ need a new Feature/ want to report a Bug, send us an email to <a href="mailTo:hello@starapps.studio">hello@starapps.studio</a>
						</p>
					</li>
					<li>
						<h3 class="card-header">
							Pricing & Plans:
						</h3>
						<p>
							<% if @plan_activeded %>
								You are currently on Unlimited Plan. 
								Your billing cycle for the app is DDth of every month.
								Read more about app billing cycle.
							<%else%>
								You are currently on <strong>Free Plan</strong>. Your billing will start when you have more than 30 products in the store.
								<br/><br/>
							<%end%>
						</p>
					</li>
					<li>
						<% if @product_count <= 30 || @plan_activeded%>
							<h3 class="card-header">
								Master Switch
							</h3>
							<div class="toggle-wrapper">

								<span class="toggle-text" id="ms-di">Disable</span>
								<div class="toggle-btn">
									<% if @shop.present? %>
										<% if @shop.enable %>
											<input type="checkbox" id="masterSwitch" name="masterSwitch" value='true' checked="true">
										<% else %>
											<input type="checkbox" id="masterSwitch" name="masterSwitch" value=''>
										<% end %>
									<% end %>
									<div class="toggle">
										<label for="masterSwitch"><i></i></label>
									</div>
								</div>
								<span class="toggle-text" id="ms-en">Enable</span>
							</div>
							<p>
								You can use this switch to disable the app in case you are not ready yet.<br/><br/>
								We recommend disabling the app using this switch in case your variant images are not displaying properly and you need our help.
							</p>
						<%else%>
							<h3 class="card-header">
								Manage Plan
							</h3>
							<div class="toggle-wrapper">
								<%= link_to 'Active Plan', plan_active_path()%>
							</div>
						<%end%>
					</li>
				</ul>
			</div>
			<div class="sidebar-info text-center">
				<strong>Need Help</strong>
				<p>
					Send us an email to <a href="mailTo:hello@starapps.studio">hello@starapps.studio</a>
				</p>
				<div class="small">
					&copy;2017 Starfruit Solution LLP All Rights Reserved.
				</div>
			</div>
		</div>
	</div>
</div>

app/views/home/plan_active.html.erb
<script type="text/javascript">
	window.top.location.href = "<%=@url%>"; 
</script>

app/views/layouts/_flash_messages.html.erb
<% content_for :javascript do %>
<script type="text/javascript">
  var eventName = typeof(Turbolinks) !== 'undefined' ? 'page:change' : 'DOMContentLoaded';

  document.addEventListener(eventName, function() {
    <% if flash[:notice] %>
      ShopifyApp.flashNotice("<%= j flash[:notice].html_safe %>");
    <% end %>

    <% if flash[:error] %>
      ShopifyApp.flashError("<%= j flash[:error].html_safe %>");
    <% end %>
  });
</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductVariantImages</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/embedded_app.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <% application_name = ShopifyApp.configuration.application_name %>
    <title><%= application_name %></title>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application', "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="app-wrapper">
      <div class="app-content">
        <main role="main">
          <%= yield %>
        </main>
      </div>
    </div>

    <%= render 'layouts/flash_messages' %>

    <script src="https://cdn.shopify.com/s/assets/external/app.js?<%= Time.now.strftime('%Y%m%d%H') %>"></script>

    <script type="text/javascript">
      ShopifyApp.init({
        apiKey: "<%= ShopifyApp.configuration.api_key %>",
        shopOrigin: "<%= "https://#{ @shop_session.url }" if @shop_session %>",
        debug: <%= Rails.env.development? ? 'true' : 'false' %>,
        forceRedirect: true
      });
    </script>

    <% if content_for?(:javascript) %>
      <div id="ContentForJavascript" data-turbolinks-temporary>
        <%= yield :javascript %>
      </div>
    <% end %>
  </body>
</html>

app/views/scripts/index.html.erb
<script type="text/javascript">
    $( document ).ready(function() {
		jQuery("#masterSwitch").on('change',function() {
		   console.log(jQuery(this).is(':checked'));
		   jQuery.get( "/update_script?shop_id=<%=@shop.try(:id)%>&enable_shop="+jQuery(this).is(':checked') );
		});
		if(jQuery("#masterSwitch").attr('value') == 'true'){
			jQuery("#masterSwitch").attr('checked', true)
		}else{
			jQuery("#masterSwitch").attr('checked', false)
		}
	});
</script>

<div class="row">
	<div class="col-sm-8 mid-col" style="padding-right: 0;">
		<section class="banner">
			<div class="banner-message text-center">
				<h1>Hello, <%=ShopifyAPI::Shop.current.shop_owner if @shop.present?%></h1>
				<p>Welcome to Variant Image Automator</p>
				<p class="small">
					Handcrafted by <strong>StarApps</strong>
				</p>
			</div>
		</section>
		<section class="setup-wrapper wrapper-padding">
			<div class="card">
				<div class="row" style="margin: 0">
					<div class="col-sm-4" id="videoTrigger" title="Play video" style="padding-left: 0; padding-right: 0;">
					    <%= image_tag 'video_thumb.png', class: 'img-responsive video-thumb'%>
					</div>
					<div class="col-sm-12 video-player" id="videoPlayer">
						<span id="closeVideo" class="close">x</span>
						<iframe width="100%" height="450" frameborder="0" allowfullscreen></iframe>
					</div>
					<div class="col-sm-8" id="videoInfo">
						<div class="card-inner">
							<h3 class="card-header">Setting up the app and products</h3>
							<p>
								This app will automatically hide images of variants not selected, after you arrange the variant images in order. Take a quick minute to learn how to arrange the product images and then it's on autopilot! 
							</p>
						</div>
					</div>
				</div>
			</div>
		</section>
		<section class="faq-wrapper wrapper-padding">
			<div class="card">
				<div class="card-inner">
					<h3 class="card-header">Frequently Asked Questions (FAQs)</h3>
					<ul class="faq-list">
						<li>
							<strong>Do i Need to change any liquid file or manually install a code?</strong>
							<p>
								No, Variant Image Automator App doesn’t require any modification in theme files.
							</p>
						</li>
						<li>
							<strong>Which themes do you support?</strong>
							<p>
								The following themes are known to work with Variant Image Automator.
								Responsive, Retina, District, Focal, Atlantic, Symmetry, Blockshop, Vantage, Sunrise, Mr Parker, ShowTime, Fashionopolism, Startup, Canopy, Editions, Expression, Envy, Colors, Alchemy, Label, Launch, Flow.
								<br/><br/>
								We are actively working to add more themes in the list, If your theme is not listed or you are having trouble with installation, send us an email to apps@starapps.studio ad we'll try our best to make it work for you.
							</p>
						</li>
						<li>
							<strong>I have products with different type of options, will that be an issue?</strong>
							<p>
								Absolutely not, the app supports upto 3 options in a product. It doesn’t matter how many different type of options you provide for different products, the app handles all of them automatically.
							</p>
						</li>
						<li>
							<strong>I have multiple images for each variant, is there any maximum limit that I can use?</strong>
							<p>
								No, you can use as many image for a variant as you wish.
							</p>
						</li>
						<li>
							<strong>Will this app reduce performance of my website or increase page load time?</strong>
							<p>
								We add a very small code in your product page and keep interactions with our server at minimum, this will not increase your page load time or affect performance.
							</p>
						</li>
					</ul>
				</div>
			</div>
		</section>
	</div>
	<div class="col-sm-4 right-col" style="padding-left: 0;">
		<div class="side-wrap">
			<div class="sidebar-wrapper">
				<ul class="sidebar-items">
					<li>
						<h3 class="card-header">
							Loving the App ?
							<%= image_tag 'heart.png'%>
						</h3>
						<p>
							Why not <a href="#">leave us a positive review!</a><br/>
							They're the main way we get recognized, and we give high-fives when we get one!
						</p>
					</li>
					<li>
						<h3 class="card-header">
							Say Hello :)
						</h3>
						<p>
							If you have a Question/ want to send us a Feedback/ need a new Feature/ want to report a Bug, send us an email to <a href="mailTo:hello@starapps.studio">hello@starapps.studio</a>
						</p>
					</li>
					<li>
						<h3 class="card-header">
							Pricing & Plans:
						</h3>
						<p>
							<% if @plan_activeded %>
								You are currently on Unlimited Plan. 
								Your billing cycle for the app is DDth of every month.
								Read more about app billing cycle.
							<%else%>
								You are currently on <strong>Free Plan</strong>. Your billing will start when you have more than 5 products in the store.
								<br/><br/>
							<%end%>
						</p>
					</li>
					<li>
						<% if @product_count <= 5 || @plan_activeded%>
							<h3 class="card-header">
								Master Switch
							</h3>
							<div class="toggle-wrapper">

								<span class="toggle-text" id="ms-di">Disable</span>
								<div class="toggle-btn">
									<% if @shop.present? %>
										<% if @shop.enable %>
											<input type="checkbox" id="masterSwitch" name="masterSwitch" value='true' checked="true">
										<% else %>
											<input type="checkbox" id="masterSwitch" name="masterSwitch" value=''>
										<% end %>
									<% end %>
									<div class="toggle">
										<label for="masterSwitch"><i></i></label>
									</div>
								</div>
								<span class="toggle-text" id="ms-en">Enable</span>
							</div>
							<p>
								You can use this switch to disable the app in case you are not ready yet.<br/><br/>
								We recommend disabling the app using this switch in case your variant images are not displaying properly and you need our help.
							</p>
						<%else%>
							<h3 class="card-header">
								Manage Plan
							</h3>
							<div class="toggle-wrapper">
								<%= link_to 'Active Plan', plan_active_path()%>
							</div>
						<%end%>
					</li>
				</ul>
			</div>
			<div class="sidebar-info text-center">
				<strong>Need Help</strong>
				<p>
					Send us an email to <a href="mailTo:hello@starapps.studio">hello@starapps.studio</a>
				</p>
				<div class="small">
					&copy;2017 Starfruit Solution LLP All Rights Reserved.
				</div>
			</div>
		</div>
	</div>
</div>

app/views/scripts/product_variants.html.erb
<main class="main-wrapper">
	<div class="app-icon-wrapper">
	    <%= image_tag 'logo.png', class: 'logo'%>
		<span>Variant Image Automator by StarApps</span>
	</div>
	<div class="row">
		<div class="col-sm-8 mid-col" style="padding-right: 0;">
			<section class="banner">
				<div class="banner-message text-center">
					<h1>Hello, Shashank.</h1>
					<p>Welcome to Variant Image Automator</p>
					<p class="small">
						Handcrafted by <strong>StarApps</strong>
					</p>
				</div>
			</section>
			<section class="setup-wrapper wrapper-padding">
				<div class="card">
					<div class="row" style="margin: 0">
						<div class="col-sm-4" id="videoTrigger" title="Play video" style="padding-left: 0; padding-right: 0;">
						    <%= image_tag 'video_thumb.png', class: 'img-responsive video-thumb'%>
						</div>
						<div class="col-sm-12 video-player" id="videoPlayer">
							<span id="closeVideo" class="close">x</span>
							<iframe width="100%" height="450" frameborder="0" allowfullscreen></iframe>
						</div>
						<div class="col-sm-8" id="videoInfo">
							<div class="card-inner">
								<h3 class="card-header">Setting up the app and products</h3>
								<p>
									This app will automatically hide images of variants not selected, after you arrange the variant images in order. Take a quick minute to learn how to arrange the product images and then it's on autopilot! 
								</p>
							</div>
						</div>
					</div>
				</div>
			</section>
			<section class="faq-wrapper wrapper-padding">
				<div class="card">
					<div class="card-inner">
						<h3 class="card-header">Frequently Asked Questions (FAQs)</h3>
						<ul class="faq-list">
							<li>
								<strong>Do i Need to change any liquid file or manually install a code?</strong>
								<p>
									No, Variant Image Automator App doesn’t require any modification in theme files.
								</p>
							</li>
							<li>
								<strong>Which themes do you support?</strong>
								<p>
									The following themes are known to work with Variant Image Automator.
									Responsive, Retina, District, Focal, Atlantic, Symmetry, Blockshop, Vantage, Sunrise, Mr Parker, ShowTime, Fashionopolism, Startup, Canopy, Editions, Expression, Envy, Colors, Alchemy, Label, Launch, Flow.
									<br/><br/>
									We are actively working to add more themes in the list, If your theme is not listed or you are having trouble with installation, send us an email to apps@starapps.studio ad we'll try our best to make it work for you.
								</p>
							</li>
							<li>
								<strong>I have products with different type of options, will that be an issue?</strong>
								<p>
									Absolutely not, the app supports upto 3 options in a product. It doesn’t matter how many different type of options you provide for different products, the app handles all of them automatically.
								</p>
							</li>
							<li>
								<strong>I have multiple images for each variant, is there any maximum limit that I can use?</strong>
								<p>
									No, you can use as many image for a variant as you wish.
								</p>
							</li>
							<li>
								<strong>Will this app reduce performance of my website or increase page load time?</strong>
								<p>
									We add a very small code in your product page and keep interactions with our server at minimum, this will not increase your page load time or affect performance.
								</p>
							</li>
						</ul>
					</div>
				</div>
			</section>
		</div>
		<div class="col-sm-4 right-col" style="padding-left: 0;">
			<div class="side-wrap">
				<div class="sidebar-wrapper">
					<ul class="sidebar-items">
						<li>
							<h3 class="card-header">
								Loving the App ?
								<%= image_tag 'heart.png'%>
							</h3>
							<p>
								Why not <a href="#">leave us a positive review!</a><br/>
								They're the main way we get recognized, and we give high-fives when we get one!
							</p>
						</li>
						<li>
							<h3 class="card-header">
								Say Hello :)
							</h3>
							<p>
								If you have a Question/ want to send us a Feedback/ need a new Feature/ want to report a Bug, send us an email to <a href="mailTo:hello@starapps.studio">hello@starapps.studio</a>
							</p>
						</li>
						<li>
							<h3 class="card-header">
								Pricing & Plans:
							</h3>
							<p>
								You are currently on <strong>Free Plan</strong>. Your billing will start when you have more than 30 products in the store.<br/>
								<strong>or</strong><br/>
								You are currently on Unlimited Plan. 
								Your billing cycle for the app is DDth of every month.
								Read more about app billing cycle <a href="#">here</a>.
								<br/><br/>
								See our plans <a href="#">here</a>.
							</p>
						</li>
						<li>
							<h3 class="card-header">
								Master Switch
							</h3>
							<div class="toggle-wrapper">
								<span class="toggle-text" id="ms-di">Disable</span>
								<div class="toggle-btn">
									<input type="checkbox" id="masterSwitch" name="masterSwitch" value="">
									<div class="toggle">
										<label for="masterSwitch"><i></i></label>
									</div>
								</div>
								<span class="toggle-text" id="ms-en">Enable</span>
							</div>
							<p>
								You can use this switch to disable the app in case you are not ready yet.<br/><br/>
								We recommend disabling the app using this switch in case your variant images are not displaying properly and you need our help.
							</p>
						</li>
					</ul>
				</div>
				<div class="sidebar-info text-center">
					<strong>Need Help</strong>
					<p>
						Send us an email to <a href="mailTo:hello@starapps.studio">hello@starapps.studio</a>
					</p>
					<div class="small">
						&copy;2017 Starfruit Solution LLP All Rights Reserved.
					</div>
				</div>
			</div>
		</div>
	</div>
</main>